# Generated by Django 3.2.4 on 2022-08-25 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField()),
                ('key', models.TextField()),
                ('SONA_code', models.TextField(default='')),
                ('mturk', models.BooleanField(default=False)),
                ('get_args', models.TextField(default='')),
                ('notes', models.TextField(default='')),
                ('study', models.TextField(default='test')),
                ('condition', models.TextField(default='')),
                ('ua_header', models.TextField(default='')),
                ('screen_width', models.TextField(default='')),
                ('screen_height', models.TextField(default='')),
                ('captcha_score', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('handedness', models.CharField(blank=True, max_length=10, null=True)),
                ('dyslexia', models.BooleanField(blank=True, null=True)),
                ('adhd', models.BooleanField(blank=True, null=True)),
                ('asd', models.BooleanField(blank=True, null=True)),
                ('vision', models.CharField(blank=True, max_length=10, null=True)),
                ('vision_reason', models.TextField(default='')),
                ('native_english', models.BooleanField(blank=True, null=True)),
                ('post_test_purpose', models.TextField(default='')),
                ('post_test_strategy', models.TextField(default='')),
                ('post_test_other', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(choices=[('IRQ', 'IRQ')], max_length=11)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('item_id', models.CharField(max_length=80)),
                ('item_type', models.CharField(blank=True, max_length=80)),
                ('version', models.CharField(blank=True, default='', max_length=80)),
                ('condition', models.CharField(blank=True, default='', max_length=80)),
                ('trial_index', models.IntegerField(blank=True, null=True)),
                ('response', models.IntegerField()),
                ('reaction_time', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vipv.participant')),
            ],
        ),
        migrations.CreateModel(
            name='BinaryChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('PV', 'Property Verification'), ('ViWM', 'Visual Working Memory'), ('AuWM', 'Auditory Working Memory')], max_length=4)),
                ('item', models.CharField(max_length=80)),
                ('item_id', models.CharField(max_length=80)),
                ('item_type', models.CharField(blank=True, max_length=80)),
                ('version', models.CharField(blank=True, default='', max_length=10)),
                ('version_id', models.CharField(max_length=80)),
                ('condition', models.CharField(blank=True, default='', max_length=80)),
                ('trial_index', models.IntegerField(blank=True, null=True)),
                ('trial_id', models.CharField(default='', max_length=10)),
                ('block_id', models.CharField(default='', max_length=10)),
                ('key_press', models.CharField(default='', max_length=10)),
                ('response', models.CharField(default='', max_length=80)),
                ('correct_response', models.CharField(default='', max_length=80)),
                ('is_correct', models.BooleanField()),
                ('reaction_time', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vipv.participant')),
            ],
        ),
    ]
