# Generated by Django 3.2.4 on 2022-09-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='list_no',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='binarychoice',
            name='task',
            field=models.CharField(choices=[('PV', 'Property Verification'), ('ViWM', 'Visual Working Memory'), ('AuWM', 'Auditory Working Mem')], max_length=4),
        ),
    ]
