# Generated by Django 3.2.4 on 2022-09-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipv', '0003_auto_20220922_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarychoice',
            name='block_id',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='binarychoice',
            name='key_press',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='binarychoice',
            name='trial_id',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='binarychoice',
            name='version',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
