# Generated by Django 3.2.4 on 2022-09-29 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipv', '0004_auto_20220928_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='post_test_variation',
            new_name='post_test_relationship',
        ),
    ]
