# Generated by Django 3.2.4 on 2022-10-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipv', '0005_rename_post_test_variation_participant_post_test_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='post_test_label_audio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participant',
            name='post_test_label_vis',
            field=models.TextField(default=''),
        ),
    ]
