# Generated by Django 3.2.4 on 2022-10-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipv', '0006_auto_20221010_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='worker_id',
            field=models.TextField(default=''),
        ),
    ]
